### ISSUE TITLE
feat: swap from milestone to iteration for sprints

### ISSUE THREAD

**Issue by opixelum** [feature-sh/bounties#29]
- [x] Check how GitHub iteration works
- [x] Remove sprint creation CI
- [x] Update `new-issues.yml` from milestones to iterations (REST to GraphQL)
    - [x] Install GitHub CLI
    - [ ] Get last issue created
    - [ ] Add current iteration

**Comment by opixelum** [comment]
[Projects Beta GraphQL docs](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects)

**Comment by n1c01a5** [comment]
This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.

**Comment by n1c01a5** [comment]
This issue was closed because it has been stalled for 5 days with no activity.
